FROM debian:12-slim@sha256:3783cc01769c7b2b1b83a5c5ad96c815348e28ed7da68e2e3687004faa906251
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential bzip2 ca-certificates xz-utils rpm2cpio cpio \
    && rm -rf /var/lib/apt/lists/*
